POST http://127.0.0.1:8000/api/post/item
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsInNpZCI6NCwiaWF0IjoxNjYwMDEwNzI1MTEwLCJleHAiOjE2NjAwNDY3MjUxMTAsImlzcyI6ImNyZWF0ZV90b2tlbiIsImluYyI6MCwia2luZCI6ImFjY2VzcyJ9.NAOgcFMafGsBp2X7jQa8kxbBgKeHmmvV04JHVvK3nQk

{
  "title": "Hello, world 2!",
  "text": "I am a iron man"
}
