POST http://127.0.0.1:8000/api/post/item
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsInNpZCI6MSwiaWF0IjoxNjU4NzU2OTg5NjUxLCJleHAiOjE2NTg3OTI5ODk2NTEsImlzcyI6ImNyZWF0ZV90b2tlbiIsImluYyI6MCwia2luZCI6ImFjY2VzcyJ9.sYEJW-mYkcJuRrxftZm2JjMZTnMZKBQGUOCwrHHQGK8

{
  "id": 0,
  "title": "Hello, world 2!",
  "text": "I am a iron man"
}
