[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
rocket = { version = "0.5.0-rc.2" }
async-std = { version = "^1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "^0.8.0"
features = [ "runtime-tokio-native-tls", "sqlx-sqlite" ]

