[package]
name = "utils"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
utils_macro = { path = "../utils_macro" }
serde = "1.0.137"
sea-orm = { version = "^0.9.0" }

[lib]
name = "utils"
path = "src/lib.rs"
